config/routes.rb
Rails.application.routes.draw do

  root 'welcomes#index'
  get 'about', to: 'welcomes#about'
  get 'workshops', to: 'welcomes#workshops'
  resources :retreats

  get 'basques', to: 'trips#basques'
  get 'berlin', to: 'trips#berlin'

end

app/models/retreat.rb
class Retreat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/retreats_controller.rb
class RetreatsController < ApplicationController

  def new
    @retreat = Retreat.new
  end

  def create

  end

  def index
    @retreats = Retreat.all
  end

  private

  def retreat_params
    params.require(:retreat).permit!
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def basques

  end

  def berlin

  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index

  end

  def about

  end

  def workshops

  end

  def basques

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Travelogue - Women Travel Groups
    %link(href="https://fonts.googleapis.com/css?family=Hammersmith+One" rel="stylesheet")
    = javascript_include_tag 'application', "data-turbolinks-track" => true

    / %link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous")
    / %link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous")


    = stylesheet_link_tag 'application', "data-turbolinks-track" => true
    = stylesheet_link_tag 'print', media: 'print'
    %script(src="https://use.fontawesome.com/672df74d4b.js")


    = csrf_meta_tags
  %body
    .navbar.navbar-top.navbar-custom.navbar-fixed-top{role: "navigation"}
      .container-fluid


        .navbar-header
          .pull-left
            %p.title= link_to 'Travelogue', root_path



        .navbar-right
          %ul.nav.navbar-nav

            %li= link_to 'About', about_path
            %li= link_to 'Workshops & Events', workshops_path
            %li.dropdown
              %a.dropdown-toggle(data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false")
                Retreats
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Surf in Basques", basques_path
                %li= link_to "Chill Hiking Retreat", berlin_path
            %li= link_to 'Blog', 'https://medium.com/travelogue-co'



= yield

app/views/layouts/home.html.haml
!!! 5
%html
  %head
    %title Travelogue - Women Travel Groups
    = stylesheet_link_tag 'application', "data-turbolinks-track" => true
    = stylesheet_link_tag 'print', media: 'print'
    %script(src="https://use.fontawesome.com/672df74d4b.js")
    = javascript_include_tag 'application', "data-turbolinks-track" => true

    %link(href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet")

    %link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous")
    %link(link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous")

    %script(src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous")

    = csrf_meta_tags
  %body

= yield

app/views/retreats/create.js.erb
window.top.location.href="<%= new_retreat_path %>"

app/views/retreats/index.html.haml
%div.retreats-show
  - @retreats.each do |retreat|
    %li= retreat.first_name
    %li= retreat.last_name
    %li= retreat.email_address
    %li= retreat.trip_name

app/views/retreats/new.html.haml
.retreat-popup
  .well
    %div.retreat-form
      = form_for @retreat do |f|
        = f.label :first_name, "First Name"
        = f.text_field :first_name
        = f.label :last_name, "Last Name"
        = f.text_field :last_name, label: "Last Name"
        = f.label :email, "Email Address"
        = f.text_field :email, label: "Email address"
        = f.hidden_field :trip_name, value: "Basque"
        %br
        %br
        = f.submit "Let's Go!", class: "btn btn-primary"

app/views/trips/basques.html.haml
%div.basques-page

  %div.background-image.carousel-color

    .carousel.event-carousel.slide{:id=>"retreatCarousel", :data => {:ride => "carousel"}}
      %ol.carousel-indicators
        %li.active{:data => {:target => "retreatCarousel", :slide_to => "0"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "1"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "2"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "3"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "4"}}


      .carousel-inner
        .item.active
          %img{:src => asset_path("bordeaux.jpg"), :alt => ""}
        .item
          %img{:src => asset_path("women_surfer.jpg"), :alt => ""}
        .item
          %img{:src => asset_path("women_surfer2.jpg"), :alt => ""}
        .item
          %img{:src => asset_path("pays-basque.jpg"), :alt => ""}
        .item
          %img{:src => asset_path("land-water.jpg"), :alt => ""}

    %div.retreat-center
      %h1.cover Retreat in the French Basques
      %h3.cover One last chance to celebrate summer to the fullest
      %a.btn.btn-primary.community-button{"data-target" => "#basquesModal", "data-toggle" => "modal", :type => "button"}
        Apply to Join!
      %div#basquesModal.modal.fade{"aria-labelledby" => "basquesModalLabel", :role => "dialog", :tabindex => "-1"}
        %div.modal-dialog{:role => "document"}
          %div.modal-content
            %div.modal-body
              %div.typeform-widget{"data-url" => "https://travelogue1.typeform.com/to/hwK5Bt", :style => "width: 100%; height: 500px;"}
              :javascript
                (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })()
              %div{:style => "font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"}
                powered by
                %a{:href => "https://www.typeform.com/examples/?utm_campaign=hwK5Bt&utm_source=typeform.com-9436401-Basic&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN", :style => "color: #999", :target => "_blank"} Typeform


            %div.modal-footer
              %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close


%ul.flex-container.basques-content
  %li.flex-item-1
    %h1 Surf Retreat to Basque Country
    %h2 September 20-25, 2017 | ~ €600
    %p You've got six days to travel with six other women. Some may be strangers but after a few days, you'll become a traveling tribe.
    %p You'll land in Bordeaux where you'll explore the city as a local, practice your French, dive into the food culture and do your best to get a little lost.
    %p From there, you'll head to Hendaye near the border of Spain. Hendaye is a surfer paradise in the Southwest of France that has a little Spanish flavor.
    %p Over the next few days you'll learn how to surf from a man named Laurent, relax on the beach and practice your yoga moves.
    %p When you've finally triumphed hopping onto a surfboard, you'll venture to Saint-Jean-de-Luz, the darling of Basques country! Here the positivity from learning something new will continue to flow like the French wine you'll surely be sipping on.
    %p As all great things end, you'll head back to Bordeaux or wherever you are off to next wrapping up a memorable trip with memorable women.
    %p Please email for a fixed price based upon room choice.
    %p= link_to "For more details visit here!", "https://www.dropbox.com/s/og3rpdhks5w9u8y/Surf-retreat-program-final.pdf?dl=0", :target => "_blank"


  %li.flex-item
    %h2 Retreat Schedule
    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Day 1
      %div.panel-body Leave Berlin and fly to Bordeaux. From there, we'll hope on a train to Hendaye to enjoy some relaxation and a nice dinner.
      %div.panel-heading
        %h3.panel-title Day 2
      %div.panel-body In Hendaye, we'll rise early to start surf lessons and enjoy some time to sit on the beach, do some yoga and explore Hendaye. In the afternoon, we'll toast one another during a wine tour.
      %div.panel-heading
        %h3.panel-title Day 3
      %div.panel-body Wake up early for the second surf lesson. Then it's a day trip to Saint Jean de Luz.
      %div.panel-heading
        %h3.panel-title Day 4
      %div.panel-body One last surfing lesson before we head to Spain for Tapas. After we get back, we'll head to Bordeux to finish up our travels.
      %div.panel-heading
        %h3.panel-title Day 5
      %div.panel-body An entire day to adventure around Bordeaux.
      %div.panel-heading
        %h3.panel-title Day 6
      %div.panel-body Head to the airport early to go home.

app/views/trips/berlin.html.haml
%div.basques-page

  %div.background-image.carousel-color

    .carousel.event-carousel.slide{:id=>"retreatCarousel", :data => {:ride => "carousel"}}
      %ol.carousel-indicators
        %li.active{:data => {:target => "retreatCarousel", :slide_to => "0"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "1"}}
        %li{:data => {:target => "retreatCarousel", :slide_to => "2"}}

      .carousel-inner
        .item.active
          %img{:src => asset_path("forest-woman.jpg"), :alt => ""}
        .item
          %img{:src => asset_path("camping-women.jpg"), :alt => ""}
        .item
          %img{:src => asset_path("coffee-fire.jpg"), :alt => ""}



    %div.retreat-center
      %h1.cover Just Chill Hiking Retreat
      %h3.cover Gettin' Out of Berlin for a Weekend Getaway
      %a.btn.btn-primary.btn-lg{"data-target" => "#berlinModal", "data-toggle" => "modal", :type => "button"}
        Apply to Join!
      %div#berlinModal.modal.fade{"aria-labelledby" => "berlinModalLabel", :role => "dialog", :tabindex => "-1"}
        %div.modal-dialog{:role => "document"}
          %div.modal-content
            %div.modal-body

              %div.typeform-widget{"data-url" => "https://travelogue1.typeform.com/to/KhxrRc", :style => "width: 100%; height: 500px;"}

              :javascript
                (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })()
              %div{:style => "font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"}
                powered by
                %a{:href => "https://www.typeform.com/examples/forms/application/?utm_campaign=KhxrRc&utm_source=typeform.com-9436401-Basic&utm_medium=typeform&utm_content=typeform-embedded-application&utm_term=EN", :style => "color: #999", :target => "_blank"} Typeform

            %div.modal-footer
              %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close



%ul.flex-container.basques-content
  %li.flex-item-1
    %h1 Chill Hiking Retreat
    %h2 August 26-27, 2017 | ~€130
    %p Tired of the hustle and unst, unst, unst of Berlin?
    %p Join us for a weekend retreat outside of the city for some time to be in nature, relax and chill the effe out!
    %p We will get a fresh perspective on the bird's eye view when we take a walk along a treetop path. Then warm up next to a cosy fire in the evening.
    %p For those needing some extra self-care and pampering, you can bike to a spa, relax at the lake or join for a hike to an abandoned building. So many choices, never enough weekend.
    %p Sound like just the thing you need? Us too.
    %p Please email for a fixed price based upon room choice.
    %p= link_to "For more details visit here!", "https://www.dropbox.com/s/i5e8cvfvxhbg59a/just-chill-hiking-retreat-program-final.pdf?dl=0", :target => "_blank"


  %li.flex-item
    %h2 Retreat Schedule
    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Day 1
      %div.panel-body Leave Berlin and head to Coconat. Lunch will be served and then we'll have a guided visit of Abandonned Die Chirurgie & Alpine Beelitz Heilstätten. After, we'll grab some bikes and head to the Baum & Zeit to walk on tops of trees. That afternoon, you'll have some free time before dinner and a cosy campfire.
      %div.panel-heading
        %h3.panel-title Day 2
      %div.panel-body Wake up for breakfast and talk about the days activities which will include a bike ride or a trip to the spa. Then we'll have lunch, some free time to visit the lake and relax. Then we'll head back to Berlin.

app/views/welcomes/about.html.haml
%div.row.about
  %h1 ABOUT
  %h3 Travelogue connects women looking to explore.

%div.about-section
  .about-information
    .row.about-one
      .col-md-4.about_photo
        %img{:src => asset_path("hana.jpg"), :class => "img-rounded hana"}
      .col-md-8.about-info
        %h2 Hana Hrz
        %h3 Founder & CEO
        %ul.links.list-unstyled
          %li
            = link_to 'hana@travelogue.com' do
              %icons.fa.fa-envelope-o
              Email
          %li
            = link_to 'https://www.instagram.com/hanahrz/' do
              %icons.fa.fa-instagram
              Instagram
        %p Hana's as zesty and spunky as the cities she's lived in: Shanghai, Berlin, Paris and Madrid. From organizing tech conferences to building communities, Hana is all about bringing people together. What's her end goal you may ask?
        %p Seeing more women hit the road and gaining more confidence while doing so.
        %p She spends all her money on travel, wine, cheese and baguettes.Lots and lots of baguettes.
        And voiláá, you have kind of, sort of met Hana.


    .row.about-two
      .col-md-4.about_photo
        %img{:src => asset_path("erinn.jpg"), :class => "img-rounded erinn"}
      .col-md-8.about-info
        %h2 Erinn Springer
        %h3 Technical Lead & Writer
        %ul.links.list-unstyled
          %li
            = link_to 'erinnlspringer@gmail.com' do
              %icons.fa.fa-envelope-o
              Email
          %li
            = link_to 'https://www.instagram.com/erinnlspringer/' do
              %icons.fa.fa-instagram
              Instagram
        %p About six years ago, Erinn quit her job, learned how to code and got a remote gig. While it's not clear which of these was the gateway drug to living out of a bag, soon Erinn became a digital nomad. After some time she's traveled a bit and lives in Berlin.
        %p Expect a mix of fun, sass and ambivert-ness from her. She doesn't believe in putting down roots or doing things in heels, but won't judge you for doing the same.

app/views/welcomes/index.html.haml
%div.flex.row
  %div.photo
    %div.logo
      %img{:src => asset_path("travelogue-full.png")}


/ %div.main
/   / %h1 A Travel Community for Women
/   %h3 Join the community that is dedicated to life-changing travel experiences for women.



%div.below-main
  %h3 Travelogue designs cozy, unique travel experiences for a social community of adventurous women.
  %input.community-button(type="button" value="Join the Community!" onclick="location.href = 'https://www.facebook.com/groups/281904978888004/';")

%div
  %ul.flex-container
    %li.flex-item
      %h3.homepage-boxes
        = link_to 'Surf Retreat in Basque Country', basques_path
      %div.image-thumbs
        %img.thumbs{:src => asset_path("bordeaux.jpg")}
    %li.flex-item
      %h3.homepage-boxes
        = link_to 'Just Chilling Retreat Near Berlin', berlin_path
      %div.image-thumbs
        %img.thumbs{:src => asset_path("women_surfer2.jpg")}
    %li.flex-item
      %h3.homepage-boxes
        = link_to 'Workshops', workshops_path
        %br
      %div.image-thumbs
        %img.thumbs{:src => asset_path("moroccoboat.jpg")}

app/views/welcomes/workshops.html.haml
%div.workshops-page
  %div.workshops
    %h1 WORKSHOPS & EVENTS
    %h3.workshop-details Travelogue brings women together for travel-related workshops, events and coffee talks. Check out some photos from our past events below!

  %div.carousel-color

    .carousel.event-carousel.slide{:id=>"myCarousel", :data => {:ride => "carousel"}}
      %ol.carousel-indicators
        %li.active{:data => {:target => "myCarousel", :slide_to => "0"}}
        %li{:data => {:target => "myCarousel", :slide_to => "1"}}
        %li{:data => {:target => "myCarousel", :slide_to => "2"}}
        %li{:data => {:target => "myCarousel", :slide_to => "3"}}
        %li{:data => {:target => "myCarousel", :slide_to => "4"}}
        %li{:data => {:target => "myCarousel", :slide_to => "5"}}


      .carousel-inner
        .item.active
          %img{:src => asset_path("southafricanfood.jpg"), :alt => ""}/
        .item
          %img{:src => asset_path("cooking_pizza.jpg"), :alt => ""}/
        .item
          %img{:src => asset_path("travel_coffee_talk.jpg"), :alt => ""}/
        .item
          %img{:src => asset_path("moroccoboat.jpg"), :alt => ""}/
        .item
          %img{:src => asset_path("marble_workshop.jpg"), :alt => ""}/
        .item
          %img{:src => asset_path("indian_yoga.jpg"), :alt => ""}/


      %a.left.carousel-control{:href => "#myCarousel", :role => "button", :data => {:slide => "prev"}}
        %span.glyphicon.glyphicon-chevron-left
        %span.sr-only Previous
      %a.right.carousel-control{:href => "#myCarousel", :data => {:slide => "next"}}
        %span.glyphicon.glyphicon-chevron-right
        %span.sr-only Next
    %input.community-button(type="button" value="Join the Community!" onclick="location.href = 'https://www.facebook.com/groups/281904978888004/';")